import { Section } from "../components/ui";
import { Ask } from "../components/Ask";

export function AskPage() {
  return (
    <Section level="h1"
      eyebrow="Urology Copilot"
      title="Ask a question in your own words"
      lead="For questions a single term does not answer — what to expect, why a test is being repeated, what to tell your family."
    >
      <Ask />
      <p className="mt-6 max-w-2xl text-xs leading-relaxed text-slate-500">
        Answers are passages from this guide, shown exactly as written, with their sources. Nothing is generated by a
        language model, so this cannot tell you something the clinical content does not say. It also cannot advise on
        your individual case — that belongs with your care team.
      </p>
    </Section>
  );
}
